# syntax=docker/dockerfile:2
FROM node:20-alpine AS base
WORKDIR /app
RUN npm install -g turbo
COPY package.json turbo.json tsconfig.base.json ./
COPY apps/client/package.json apps/client/
COPY packages/shared/package.json packages/shared/
RUN npm install --omit=dev

FROM base AS builder
COPY --prune=hard ./ ./
RUN turbo run build --filter=@willyboxd/shared --filter=@willyboxd/client

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=builder /app/apps/client/dist /app/dist

FROM nginx:alpine AS final
COPY --from=runner /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
